# AUTOGENERATED! DO NOT EDIT! File to edit: nbs/01_vision.ipynb (unless otherwise specified).

__all__ = ['arr2im']

# Cell

import PIL

def arr2im(arr):
    "Convert array to PIL image"
    return PIL.Image.fromarray(arr,mode='RGB')